manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.1  # <-- 다시 v0.1로 두거나, 아래의 브랜치 방식으로 시도합니다.
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main     
  self:
    path: config
